---
title: "Correlation Analysis. Iteration 2."
author: Cindy Ramírez, Carlos Dávila.
output: html_document
---

```{r warning=FALSE, message=FALSE, echo=FALSE}
# Work Space preparation
library(tidyverse)
library(data.table)
library(GGally)
library(rmarkdown)

source("tools.R")
```

## Aim of the study

The main goal of this study is to **analyse the correlations between already created MJC Criteria** (¿indicators?). 

MJC Criteria are sustainable development indicators aimed to split the pie of the Carbon Dioxide Emissions from the Carbon Dioxide Emissions Budget stablished to avoid the Earth temperature raise over 2ºC in regard to the current before 2100.

## Conditions of the analysis.

The following is an oversimplification of the theoretical framework of interest for the analysis, focused on clarifying the requirements of this study.

### Parametric and non-parametric statistics

The difference between parametric and non-parametric statistics is that in the first one the population's distributions are known, while in the second they are not.

### Correlation between variables

Correlations between two random variables occur when the two variables are **linearly related** to each other. A correlation exists if changes in the value of the variable A happens at the same proportion than in the variable B.

### Pearson's $\mathcal{r}$ correlation coefficient (parametric)

In statistics, the Pearson's $\mathcal{r}$ is a statistic that **measures linear correlation between two variables X and Y**.

Pros:

* 

Cons:

* We need the variables to be bivariate normally distributed
* The presence of outliers skewes the coefficient obtained

### Spearman's $\rho$ correlation coefficient (non-parametric)

Spearman's $\rho$ correlation coefficient is a correlation measure about the association or interdependecy of two random variables.

To calculate $\rho$ data is ordered and replaced by its respective relative order position.

Pros:

* Data do not need to follow any known distribution
* We get an aproximation of the interpendency of each pair of variables

Cons:

* Distances between countries are lost as the magnitudes of the variables are replaced by a ranking position.

### Kendall rank's $\tau$ correlation coefficient (non-parametric)

Kendall rank's $\tau$ correlation coefficient is a statistic used to measure the ordinal association between two measured quantities. It is a non-parametric technique. It does not apply in this case.

## Data fitness to conditions

### Goodness of fit of data distributions

Thus, to perform a correlation analysis based on pearson's $\mathcal{r}$ we must verify that the distributions of the variables are normal.

## Alternative?


